Add controllers
gauharbegim/java-shareit pull request #6
Opened 2023-02-14 11:43 UTC by gauharbegim

2023-02-15 08:54 UTC, AnastasiyaFomkina requested changes

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Collection<ItemDto> getItems(@RequestHeader(value = "X-Sharer-User-Id") Integer ownerId) {
`"X-Sharer-User-Id"` лучше вынести в отдельный утильный класс `Variables` и сделать публичной константой, чтобы избежать дублирований. 
В будущих спринтах он нам понадобиться не только в этом контроллере, поэтому лучше заранее вынести его в отдельный класс

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   */
В коммерческой разработке, когда код из `TODO` реализован, принято его удалять, чтобы он не путал других разработчиков.
Удали, пожалуйста, все `TODO`, которые были выполнены во всем проекте

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dao/ItemStorageImpl.java
> +    private HashMap<Integer, Item> items = new HashMap<>();
1) Может быть [final](https://vertex-academy.com/tutorials/ru/modifikator-final/)
2) Лучше обозначать интерфейс, а уже инициализировать объект с определенной реализацией. Так программа становится более гибкой и не сломается, если нужно будет подменить реализацию на другую
```suggestion
    private Map<Integer, Item> items = new HashMap<>();
```

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dao/ItemStorageImpl.java
> +    public Map<Integer, Item> getItems(Integer ownerId) {
Метод должен возвращать список предметов

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dao/ItemStorageImpl.java
> +        for (Item item : items.values()) {
Нужно будет переписать поиск с помощью [stream api](https://habr.com/ru/company/otus/blog/658999/)

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public static Collection<ItemDto> toItemDtoCollection(Map<Integer, Item> itemMap) {
Этот метод лишний, нужно сразу возвращать список, а не создавать промежуточную мапу

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
Нужно добавить валидацию для полей

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dao/ItemStorageImpl.java
> +    public Map<Integer, Item> getItems(String text) {
Этот метод тоже должен сразу возвращать список

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dao/ItemStorageImpl.java
> +        for (Item item : items.values()) {
Используй stream api

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/exceptions/IncorrectUserParameterException.java
> +    public IncorrectUserParameterException(String parameter) {
Конструктор и геттер нужно создавать с помощью [lombok](https://habr.com/ru/company/piter/blog/676394/)

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/exception/IncorrectItemParameterException.java
> +    public IncorrectItemParameterException(String parameter) {
Конструктор и геттер нужно создавать с помощью [lombok](https://habr.com/ru/company/piter/blog/676394/)

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/exception/IncorrectOwnerParameterException.java
> +    public IncorrectOwnerParameterException(String parameter) {
Конструктор и геттер нужно создавать с помощью [lombok](https://habr.com/ru/company/piter/blog/676394/)

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    Collection<ItemDto> getItems(Integer ownerId);
Лучше использовать `List` вместо `Collection`, так как `Collection` слишком абстрактный.
Замени, пожалуйста, везде, где используется `Collection`

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/ErrorHandler.java
> +    public ErrorResponse handleIncorrectOwnerParameterException(final IncorrectOwnerParameterException e) {
Нужно переименовать название параметра по `code-style`.
Использовать однобуквенные переменные и сокращения считается `code smell` в коммерческой разработке, так как подобный нейминг делает код менее читаемым

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserStorage.java
> +    private HashMap<Integer, User> users = new HashMap<>();
1) Может быть [final](https://vertex-academy.com/tutorials/ru/modifikator-final/)
2) 
```suggestion
    private Map<Integer, User> users = new HashMap<>();
```

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserStorage.java
> +        for (User user : users.values()) {
Нужно использовать stream api

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/ErrorResponse.java
> +    public ErrorResponse(String error) {
Конструктор и геттер нужно создавать с помощью [lombok](https://habr.com/ru/company/piter/blog/676394/)

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserStorage.java
> +        if (users.containsKey(id)) {
Лучше использовать встроенный метод мапы [getOrDefault](https://www.geeksforgeeks.org/hashmap-getordefaultkey-defaultvalue-method-in-java-with-examples/). Он возвращает значение по ключу, если оно есть, или дефолтное значения, если нет

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserStorage.java
> +    public Map<Integer, User> getUsers() {
Должен возвращать список

2023-02-15 08:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +    public static Collection<UserDto> toUserDtoCollection(Map<Integer, User> userMap) {
Данный метод будет ненужен, когда мы начнем сразу возвращать список, вместо мапы

2023-02-15 11:15 UTC, gauharbegim commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
я ранее добавляла 
но далее он не проходит тесты 

если при создании нельзя передавать пустое название 
то при апдейте это возможно 
по этой причине я добавила флк в сервисе

2023-02-16 13:06 UTC, AnastasiyaFomkina requested changes

2023-02-16 13:06 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserStorage.java
> +        for (User user : users.values()) {
Используй [stream api filter](https://vertex-academy.com/tutorials/ru/java-8-stream-filter/)

2023-02-16 13:06 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +        for (User user : userList) {
Используй `map stream api` и уже готовый метод `toUserDto`, как в маппере предметов

2023-02-16 13:06 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/utilits/Variables.java
> +    public static final String USER_ID = "X-Sharer-User-Id";
🔥

2023-02-16 13:06 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dao/ItemStorageImpl.java
> +        return items.values().stream().filter(item -> item.getOwner().equals(user)).collect(Collectors.toList());
Для лучшей читаемости кода, принято бить стрим по методам:
```suggestion
        return items.values().stream()
            .filter(item -> item.getOwner().equals(user))
            .collect(Collectors.toList());
```

2023-02-16 13:06 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dao/ItemStorageImpl.java
> +        return items.values().stream().filter(item -> item.getIsAvailable()
```suggestion
        return items.values().stream()
            .filter(item -> item.getIsAvailable()
```

2023-02-16 13:06 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dao/ItemStorageImpl.java
> +        Item item = items.get(id);
Можно не создавать лишнюю переменную, а сразу возвращать результат работы метода:
```suggestion
        return items.get(id);
```

2023-02-17 04:51 UTC, gauharbegim commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +        for (User user : userList) {
perfect

2023-02-26 14:00 UTC, merged