modify: add server gateway
gauharbegim/java-shareit pull request #9
Opened 2023-05-27 12:55 UTC by gauharbegim

2023-05-28 15:30 UTC, afomkina requested changes
Не проходят тесты, нужно починить код, а потом снова отправить работу на ревью

2023-05-29 22:56 UTC, AnastasiyaFomkina requested changes

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingStatus.java
> +public enum BookingStatus {
Нигде не используется

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +            headers.set("X-Sharer-User-Id", String.valueOf(userId));
Нужно использовать константу `USER_ID`

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public ResponseEntity<Object> createItemRequest(@RequestHeader("X-Sharer-User-Id") Integer userId,
`"X-Sharer-User-Id"` - нужно использовать константу `USER_ID`, а не дублировать одну и ту же строку здесь и ниже

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<Object> getItems(@RequestHeader("X-Sharer-User-Id") Integer userId) {
Нужно использовать константу `USER_ID` здесь и ниже

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on gateway/src/main/resources/application.properties
> +#logging.level.httpclient.wire=DEBUG
Нужно удалить неиспользуемые параметры

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>      @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
Из модуля `server` нужно удалить всю валидацию dto, так как она переехала в модуль `gateway`. Не забудь удалить лишние зависимости из pom файла данного модуля

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookingStatus.java
> +public enum BookingStatus {
Нигде не используется

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +//    @Override
Неиспользуемый код нужно удалить

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            log.info("*****************************************************");
Логи для дебага нужно удалить

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return list.stream().map(BookingMapper::toBookingDto).collect(Collectors.toList());
Стримы принято бить по строкам для лучшей читаемости кода
```suggestion
        return list.stream()
            .map(BookingMapper::toBookingDto)
            .collect(Collectors.toList());
```

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/comment/model/Comment.java
> +import javax.persistence.*;
Нужно избавиться от [wildcard](https://struchkov.dev/blog/using-wildcard-imports-in-java/) в импортах

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +//        Map<Long, List<CommentDto>> comments = commentRepository.findByItemIdIn(idItems, Sort.by(DESC, "created"))
Весь закомментированный код нужно удалить

2023-05-29 22:56 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/request/dao/ItemRequestRepository.java
> +//    @Query(nativeQuery = true, value = "SELECT * from (SELECT b.*, ROWNUM() r FROM (SELECT b.* FROM REQUESTS b WHERE b.USER_ID<>:user ORDER BY DATE_CREATE DESC ) b ) " +
Закомментированный код нужно удалить

2023-05-30 13:54 UTC, AnastasiyaFomkina requested changes
Из модуля `server` нужно удалить всю валидацию `dto`, так как она переехала в модуль `gateway`. Не забудь удалить лишние зависимости из pom файла данного модуля

2023-05-31 18:56 UTC, AnastasiyaFomkina approved these changes

2023-06-01 13:15 UTC, merged